name: Linux Release Pipeline

on:
  release:
    types: [published]
permissions:
  contents: write # release changes require contents write

env:
  DOTNET_VERSION: '9.x'
  SOLUTION_PATH: 'tsqlsharpcli.sln'
  PROJECT_PATH: 'src/tsqlsharp-formatter-cli.csproj'

jobs:
      
  build:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }}
          --configuration Release
      
      - name: publish
        run: dotnet publish -r linux-x64 -c Release -p:PublishSingleFile=true -p:AssemblyName=tsqlsharp-formatter -o ./

      - name: package cli
        run: | 
          chmod +x tsqlsharp-formatter
          tar -czvf tsqlsharp-formatter-${{ github.event.release.tag_name }}-linux-amd64.tar.gz tsqlsharp-formatter

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload ${{ github.event.release.tag_name }} tsqlsharp-formatter-${{ github.event.release.tag_name }}-linux-amd64.tar.gz